#!/usr/bin/env python3
"""Import KM-exported HTML articles into this Hexo knowledge base.

- Reads HTML files from ~/Documents/kubernetes and ~/Documents/linux by default
- Extracts the main article body from the KM export HTML
- Cleans title metadata to remove company / department / platform suffixes
- Writes imported articles into source/_posts/<category>/
"""

from __future__ import annotations

import argparse
import hashlib
import re
import shutil
from dataclasses import dataclass
from datetime import datetime
from html.parser import HTMLParser
from pathlib import Path
from typing import Iterable, Optional
from urllib.parse import unquote


DEFAULT_SOURCES = {
    "kubernetes": Path("/Users/ab000664/Documents/kubernetes"),
    "linux": Path("/Users/ab000664/Documents/linux"),
    "es": Path("/Users/ab000664/Documents/es"),
}

REPO_ROOT = Path(__file__).resolve().parents[1]
POSTS_ROOT = REPO_ROOT / "source" / "_posts"
ASSETS_ROOT = REPO_ROOT / "source" / "images"
README_SENTINEL = "<!-- generated by import_km_html.py -->"


def _detect_site_root() -> str:
    """Read site root from _config.yml so generated <img src> works whether the
    Hexo site is served at / or under a subpath (e.g. GitHub Pages /logbook/).
    Returns a string starting and ending with '/'.
    """
    config = REPO_ROOT / "_config.yml"
    root = "/"
    if config.is_file():
        text = config.read_text(encoding="utf-8", errors="ignore")
        m = re.search(r"^root:\s*(\S+)", text, re.MULTILINE)
        if m:
            root = m.group(1).strip().strip('"').strip("'")
        else:
            m = re.search(r"^url:\s*(\S+)", text, re.MULTILINE)
            if m:
                url = m.group(1).strip().strip('"').strip("'")
                path = re.sub(r"^[a-zA-Z]+://[^/]+", "", url)
                root = path or "/"
    if not root.startswith("/"):
        root = "/" + root
    if not root.endswith("/"):
        root = root + "/"
    return root


SITE_ROOT = _detect_site_root()

# <img> with these class tokens are decoration (avatar / QR / KM iconography)
# and should be removed entirely instead of being copied as assets.
IMAGE_DECORATION_CLASS_PATTERNS = [
    r"\bavatar\b",
    r"\bhas-apply-img\b",
    r"\bkm[_-]?headline\b",
    r"\bheadline[_-]?icon\b",
    r"\bqr[_-]?code\b",
    r"\bsprite\b",
    r"\bicon-",
]

IMG_TAG_RE = re.compile(r"<img\b[^>]*?/?>", re.IGNORECASE)
IMG_SRC_RE = re.compile(r'src\s*=\s*"([^"]*)"', re.IGNORECASE)
IMG_CLASS_RE = re.compile(r'class\s*=\s*"([^"]*)"', re.IGNORECASE)

# Magic-byte sniffing so extension-less files (e.g. cos-file-url(3)) get the
# right suffix when copied into the Hexo asset tree.
_IMAGE_MAGIC: list[tuple[bytes, str]] = [
    (b"\x89PNG\r\n\x1a\n", "png"),
    (b"\xff\xd8\xff", "jpg"),
    (b"GIF87a", "gif"),
    (b"GIF89a", "gif"),
    (b"BM", "bmp"),
    (b"<svg", "svg"),
    (b"<?xml", "svg"),
]


def sniff_image_ext(data: bytes) -> Optional[str]:
    head = data[:32]
    for magic, ext in _IMAGE_MAGIC:
        if head.startswith(magic):
            return ext
    if head.startswith(b"RIFF") and data[8:12] == b"WEBP":
        return "webp"
    return None


def _normalize_code_blocks(content: str) -> str:
    """Flatten KM-flavored <pre><code>…</code></pre> blocks.

    KM exports color the source by wrapping every token in nested
    <span style="color:…">…</span>. hexo-renderer-marked treats anything
    inside <pre><code> as raw code text and HTML-escapes it, so those spans
    end up rendered as literal `<span style=...>` strings on the site.

    Strip every inline <span> (keeping text), and clear inline style/class on
    <pre> and inner <code> so the theme's syntax styles can apply cleanly.
    """

    def _clean(match: re.Match) -> str:
        inner = match.group(1)
        # Drop nested spans (KM nests them deeply).
        prev = None
        while prev != inner:
            prev = inner
            inner = re.sub(r"<span\b[^>]*>", "", inner, flags=re.IGNORECASE)
            inner = re.sub(r"</span>", "", inner, flags=re.IGNORECASE)
        # Convert <br> to a literal newline so it survives marked escaping.
        inner = re.sub(r"<br\s*/?>", "\n", inner, flags=re.IGNORECASE)
        # Normalize <code ...> -> <code>
        inner = re.sub(r"<code\b[^>]*>", "<code>", inner, flags=re.IGNORECASE)
        # Strip any remaining inline tags (e.g. <font>, <b>, <i>, <em>, <a>);
        # keep <code>/</code> intact.
        inner = re.sub(
            r"<(?!/?code\b)/?[a-zA-Z][^>]*>",
            "",
            inner,
            flags=re.IGNORECASE,
        )
        return f"<pre>{inner}</pre>"

    return re.sub(r"<pre\b[^>]*>([\s\S]*?)</pre>", _clean, content, flags=re.IGNORECASE)


TITLE_FILTER_PATTERNS = [
    r"字节跳动旗下产品",
    r"字节跳动",
    r"今日头条",
    r"西瓜视频",
    r"抖音",
    r"火山短视频",
    r"微信",
    r"腾讯云",
    r"腾讯",
]

# Company / department / team phrases that may appear in body content as
# attribution and should be scrubbed when importing into the personal repo.
CONTENT_ORG_PATTERNS = [
    r"WXG技术能力提升",
    r"WXG",
    r"PCG\s*Kbang\s*知识分享平台",
    r"Elasticsearch实验室",
    r"基础架构部",
    r"腾讯云大数据基础产品",
    r"腾讯云大数据及人工智能",
    r"自研业务上云",
    r"Ulink游戏营销技术",
    r"腾讯公司研发管理部",
    r"字节跳动旗下产品",
    r"字节跳动",
    r"今日头条",
    r"西瓜视频",
    r"抖音",
    r"火山短视频",
    r"微视",
    r"微信",
    r"腾讯云",
    r"腾讯",
]

CONTENT_TRUNCATION_MARKERS = [
    'class="update-time"',
    'class="knowledge-apply-mod',
    "<!--知识申报模块-->",
    "<!-- 微信二维码推广模块 -->",
    'element_name="qr_code_share.thtml"',
    'element_name="related_posts.thtml"',
    'id="related-posts"',
    'id="operations"',
    'id="share_list"',
    'id="post2k_div"',
    'id="reship_div"',
    'id="mail_div"',
    "腾讯公司研发管理部 版权所有",
]


class ElementInnerHTMLExtractor(HTMLParser):
    def __init__(self, target_id: str):
        super().__init__(convert_charrefs=False)
        self.target_id = target_id
        self.depth = 0
        self.capturing = False
        self.parts: list[str] = []

    def handle_starttag(self, tag: str, attrs):
        attrs_dict = dict(attrs)
        if not self.capturing and attrs_dict.get("id") == self.target_id:
            self.capturing = True
            self.depth = 1
            return
        if self.capturing:
            self.depth += 1
            self.parts.append(self.get_starttag_text())

    def handle_startendtag(self, tag: str, attrs):
        if self.capturing:
            self.parts.append(self.get_starttag_text())

    def handle_endtag(self, tag: str):
        if not self.capturing:
            return
        self.depth -= 1
        if self.depth == 0:
            self.capturing = False
            return
        self.parts.append(f"</{tag}>")

    def handle_data(self, data: str):
        if self.capturing:
            self.parts.append(data)

    def handle_entityref(self, name: str):
        if self.capturing:
            self.parts.append(f"&{name};")

    def handle_charref(self, name: str):
        if self.capturing:
            self.parts.append(f"&#{name};")

    def handle_comment(self, data: str):
        if self.capturing:
            self.parts.append(f"<!--{data}-->")

    def handle_decl(self, decl: str):
        if self.capturing:
            self.parts.append(f"<!{decl}>")

    def handle_pi(self, data: str):
        if self.capturing:
            self.parts.append(f"<?{data}>")

    def inner_html(self) -> str:
        return "".join(self.parts)


@dataclass
class ImportedArticle:
    category: str
    title: str
    source_path: Path
    output_path: Path


def clean_title(raw_name: str) -> str:
    title = re.sub(r"\.(html?|pdf)$", "", raw_name, flags=re.IGNORECASE)
    title = re.sub(r"\.pdf(?=\s*-|$)", "", title, flags=re.IGNORECASE)
    title = re.sub(r"\s*-\s*KM平台$", "", title)
    title = re.sub(r"^[【\[].*?[】\]]\s*", "", title)
    if " - " in title:
        title = re.sub(r"\s*-\s*[^-]+$", "", title)
    for pattern in TITLE_FILTER_PATTERNS:
        title = re.sub(pattern, "", title)
    title = re.sub(r"([，、（(])\s*[，、]\s*", r"\1", title)
    title = re.sub(r"\s+", " ", title)
    title = re.sub(r"([，、（(])\s+", r"\1", title)
    title = re.sub(r"\s+([）)])", r"\1", title)
    title = re.sub(r"^[，、\-\s]+", "", title)
    title = re.sub(r"[，、\-\s]+$", "", title)
    title = re.sub(r"\s+", " ", title).strip(" -_")
    return title


def safe_filename(title: str) -> str:
    value = title.strip()
    value = value.replace("/", "／").replace("\\", "＼")
    value = value.replace(":", "：").replace("?", "？")
    value = value.replace("*", "＊").replace('"', "＂")
    value = value.replace("<", "＜").replace(">", "＞").replace("|", "｜")
    value = re.sub(r"\s+", " ", value).strip()
    return value or "untitled"


def cleanup_article_html(content: str) -> str:
    cut_positions = [content.find(marker) for marker in CONTENT_TRUNCATION_MARKERS if marker in content]
    if cut_positions:
        content = content[: min(cut_positions)]

    content = _normalize_code_blocks(content)

    patterns = [
        r"<div[^>]*class=\"watermark\"[^>]*>\s*</div>",
        r"<div[^>]*class=\"cl-preview-section\"[^>]*>\s*<nav[^>]*class=\"table-of-contents\"[\s\S]*?</nav>\s*</div>",
        r"<span[^>]*element_name=\"[^\"]+\.thtml(?:-start|-end)?\"[^>]*>\s*</span>",
        r"<cake:nocache>[\s\S]*?</cake:nocache>",
        r"<script[\s\S]*?</script>",
        r"<style[\s\S]*?</style>",
        r"<template[\s\S]*?</template>",
        r"<div[^>]*id=\"related-posts\"[\s\S]*?</div>\s*(?=<|$)",
        r'<div[^>]*class="related_posts[^"]*"[\s\S]*?</div>',
        r"<link[^>]+rel=\"stylesheet\"[^>]*>",
        r"<img[^>]*src=\"\./[^\"]+_files/[^\"]+\.(?:gif|png|jpg|jpeg|svg)\"[^>]*>\s*",
    ]
    for pattern in patterns:
        content = re.sub(pattern, "", content, flags=re.IGNORECASE)

    content = re.sub(r"\s*<div[^>]*class=\"cl-preview-section\"[^>]*>\s*</div>\s*", "\n", content, flags=re.IGNORECASE)
    content = re.sub(r"<div[^>]*class=\"cl-preview-section\"[^>]*>", "", content, flags=re.IGNORECASE)
    content = re.sub(r"</div>\s*(?=(<h\d|<p|<pre|<ul|<ol|<table|<blockquote|<figure|<img|<hr|$))", "\n\n", content, flags=re.IGNORECASE)
    content = re.sub(r"<div[^>]*class=\"(?:js_operations_bar|qr-code-share|digg_favor|hide)\"[^>]*>[\s\S]*?</div>", "", content, flags=re.IGNORECASE)

    lines = content.splitlines()
    while lines:
        while lines and not lines[-1].strip():
            lines.pop()
        removed = False
        while lines and re.fullmatch(r"(?:\s*</div>\s*)+", lines[-1]):
            lines.pop()
            removed = True
        while lines and re.fullmatch(r"\s*<div[^>]*", lines[-1]):
            lines.pop()
            removed = True
        if not removed:
            break
    content = "\n".join(lines)

    content = re.sub(r"\n{3,}", "\n\n", content)
    content = scrub_org_mentions(content)
    return content.strip()


def scrub_org_mentions(content: str) -> str:
    """Remove obvious company/department attribution from article body."""
    for pattern in CONTENT_ORG_PATTERNS:
        # Strip standalone attribution lines like "—— 腾讯xxx" / "作者：腾讯xxx".
        content = re.sub(
            rf"(?m)^[\s>]*(?:作者[:：]|来源[:：]|—+|--+)?\s*{pattern}.*$",
            "",
            content,
        )
        # Inline removal of brand mentions inside running text.
        content = re.sub(pattern, "", content)
    content = re.sub(r"[ \t]+\n", "\n", content)
    content = re.sub(r"\n{3,}", "\n\n", content)
    return content


def extract_article_html(html_text: str) -> str:
    for target in ("mce_view_content", "article_content"):
        parser = ElementInnerHTMLExtractor(target)
        parser.feed(html_text)
        parser.close()
        content = parser.inner_html().strip()
        if content:
            break
    else:
        if any(marker in html_text for marker in ("doc_preview", ".pdf", "pdf_preview", "img_preview")):
            return (
                "<blockquote>\n"
                "<p>该条目来自 KM 导出的 PDF 预览页，HTML 中未包含可直接提取的正文文本。"
                "后续如需完整内容，建议补充原始 PDF 或可复制文本版本。</p>\n"
                "</blockquote>"
            )
        raise ValueError("Could not locate article content container")

    return cleanup_article_html(content)


def build_front_matter(title: str, category: str, source_path: Path) -> str:
    dt = datetime.fromtimestamp(source_path.stat().st_mtime).strftime("%Y-%m-%d %H:%M:%S")
    return (
        "---\n"
        f"title: {yaml_escape(title)}\n"
        f"date: {dt}\n"
        "categories:\n"
        f"  - {category}\n"
        "---\n\n"
    )


def yaml_escape(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def iter_source_files(path: Path) -> Iterable[Path]:
    if not path.exists():
        return []
    return sorted(
        p
        for p in path.glob("*.htm*")
        if p.is_file() and not p.name.startswith("saved_resource")
    )


def write_article(category: str, source_path: Path, overwrite: bool = True) -> ImportedArticle:
    title = clean_title(source_path.name)
    destination_dir = POSTS_ROOT / category
    destination_dir.mkdir(parents=True, exist_ok=True)
    slug = safe_filename(title)
    output_path = destination_dir / f"{slug}.md"

    html_text = source_path.read_text(encoding="utf-8", errors="ignore")
    article_html = extract_article_html(html_text)
    article_html = process_images(article_html, source_path, category, slug)
    body = build_front_matter(title, category, source_path) + article_html + "\n"

    if overwrite or not output_path.exists():
        output_path.write_text(body, encoding="utf-8")

    return ImportedArticle(category=category, title=title, source_path=source_path, output_path=output_path)


def process_images(html: str, source_path: Path, category: str, slug: str) -> str:
    """Copy referenced _files/<asset> images into source/images/<cat>/<slug>/
    and rewrite <img src> to a site-root URL Hexo will serve. Drop decoration
    images (avatars, QR codes, KM iconography) and templated/broken refs.
    """
    source_dir = source_path.parent
    dest_dir = ASSETS_ROOT / category / slug
    # Reset asset dir so stale images from previous runs don't accumulate.
    if dest_dir.exists():
        shutil.rmtree(dest_dir)

    def is_decoration(tag: str) -> bool:
        cls_match = IMG_CLASS_RE.search(tag)
        if not cls_match:
            return False
        cls = cls_match.group(1)
        return any(re.search(pat, cls, re.IGNORECASE) for pat in IMAGE_DECORATION_CLASS_PATTERNS)

    def replace(match: re.Match) -> str:
        tag = match.group(0)
        if is_decoration(tag):
            return ""
        src_match = IMG_SRC_RE.search(tag)
        if not src_match:
            return tag
        src = src_match.group(1).strip()
        if not src or src.startswith("<%") or src.startswith("data:"):
            return ""
        if "_files/" not in src:
            # Leave external/absolute URLs alone (rare but safe to keep).
            if src.startswith(("http://", "https://", "//")):
                return tag
            return ""

        rel = unquote(src)
        if rel.startswith("./"):
            rel = rel[2:]
        local_path = (source_dir / rel).resolve()
        if not local_path.is_file():
            return ""

        data = local_path.read_bytes()
        ext = sniff_image_ext(data)
        if not ext:
            suffix = local_path.suffix.lower().lstrip(".")
            if suffix in {"png", "jpg", "jpeg", "gif", "svg", "webp", "bmp"}:
                ext = "jpg" if suffix == "jpeg" else suffix
            else:
                return ""

        digest = hashlib.md5(data).hexdigest()[:12]
        dest_name = f"{digest}.{ext}"
        dest_dir.mkdir(parents=True, exist_ok=True)
        dest_path = dest_dir / dest_name
        if not dest_path.exists():
            dest_path.write_bytes(data)

        url = f"{SITE_ROOT}images/{category}/{slug}/{dest_name}"
        return IMG_SRC_RE.sub(f'src="{url}"', tag, count=1)

    return IMG_TAG_RE.sub(replace, html)


def update_readme(imported: list[ImportedArticle]) -> None:
    grouped: dict[str, list[ImportedArticle]] = {}
    for article in imported:
        grouped.setdefault(article.category, []).append(article)

    lines = [
        "# logbook",
        "",
        "个人知识库（Hexo）。",
        "",
        "## 导入 HTML 文章",
        "",
        "来源目录默认使用：",
        "",
        "- `~/Documents/kubernetes`",
        "- `~/Documents/linux`",
        "- `~/Documents/es`",
        "",
        "执行导入：",
        "",
        "```zsh",
        "python3 tools/import_km_html.py",
        "```",
        "",
        "本地预览：",
        "",
        "```zsh",
        "npm install",
        "npm run server",
        "```",
        "",
        "## 已导入分类",
        "",
        README_SENTINEL,
        "",
    ]

    for category in sorted(grouped):
        lines.append(f"### {category}")
        lines.append("")
        for article in sorted(grouped[category], key=lambda item: item.title):
            rel = article.output_path.relative_to(REPO_ROOT)
            lines.append(f"- `{rel}`")
        lines.append("")

    (REPO_ROOT / "README.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Import KM HTML articles into Hexo posts")
    parser.add_argument("--kubernetes-dir", default=str(DEFAULT_SOURCES["kubernetes"]))
    parser.add_argument("--linux-dir", default=str(DEFAULT_SOURCES["linux"]))
    parser.add_argument("--es-dir", default=str(DEFAULT_SOURCES["es"]))
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    sources = {
        "kubernetes": Path(args.kubernetes_dir).expanduser(),
        "linux": Path(args.linux_dir).expanduser(),
        "es": Path(args.es_dir).expanduser(),
    }

    imported: list[ImportedArticle] = []
    for category, source_dir in sources.items():
        files = list(iter_source_files(source_dir))
        for source_path in files:
            imported.append(write_article(category, source_path))

    update_readme(imported)

    print(f"Imported {len(imported)} article(s)")
    for article in imported:
        print(f"- [{article.category}] {article.title} -> {article.output_path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()

